### ISSUE TITLE
Ошибка в запросе

### ISSUE THREAD

**Issue by kozlyakov-m** [ABashkirova/model-auth-app#39]
https://github.com/ABashkirova/model-auth-app/blob/7330d203603c06292db28db17f371ec65c01e85e/app/src/main/kotlin/xyz/sashenka/modelauthapp/dao/ResourceDAO.kt#L16

java -jar app.jar -login sasha -pass 123 -role READ -res AA
выдает SUCCESS  вместо ACCESS_DENIED, хотя ресурса AA нет, только A

**Comment by ABashkirova** [comment]
Пофикшено в #40
